sudo: required

language: generic

git:
  depth: false

dist: xenial

cache:
  directories:
    - $HOME/.m2

services:
  - docker

script:
  - travis_retry docker run -v $PWD:/src -v $HOME/.m2:/root/.m2 -e BRANCH=$TRAVIS_BRANCH -e VAULT_TOKEN=$VAULT_TOKEN moussavdb/build-java:21
